### PR TITLE
[FIX PERMISSION]

### PR DESCRIPTION
**Pull request by mapy69003**
No one could be able to modify a watchlist that doesn't belong to him

### CODE REVIEW

**Comment by mapy69003** [comment]
@vseguin @wfortin I can't assign you to this PR.
So in case you guys don't receive a notification about this PR, I tag you there.

**Comment by wfortin** [comment]
LGTM but I don't think this will work on the _unsecure_ mode, since you're relying on the user.id

We can merge that but we'll need to have a way to make it work with unsecure also.
@vseguin what do you think?

**Comment by vseguin** [comment]
I think it needs to work with unsecure before merging.

**Comment by wfortin** [comment]
@mapy69003 can you handle that?

**Comment by mapy69003** [comment]
I'll see

**Comment by mapy69003** [comment]
Done with unsecure @wfortin @vseguin

**Comment by mapy69003** [comment]
Don't merge, there is an error

**Comment by wfortin** [comment]
Thanks @mapy69003 this will deploy shortly.

**Pull request merged**
